### PR TITLE
Copy report.php instead of linking it, to avoid relative path problems

### PR DESCRIPTION
**Pull request by tmotyl**
with symlinks in require statement.

### CODE REVIEW

**Comment by zefer** [comment]
@tmotyl Thanks for this contribution. It's not clear to me what problem or error this solves. Can you please give details?

Looking at https://github.com/colinmollenhour/modman - I don't think we should be doing any copying here, symlinks are the intended usage, unless I'm mistaken?

**Comment by tmotyl** [comment]
Hi @zefer 
yes, usually symlinks are the way to go.
However in report.php file there is a line:
"require_once 'processor.php';"

So, if you run 
```
modman deploy-all --force
```
then the report.php file will be overriten with a symlink.
So PHP will be looking for the processor.php file relative to the Airbrake_Magento folder instead of the 'errors' folder

**Comment by kyrylo** [comment]
From my understanding this change is supposed to fix this error, isn't it?

```
Fatal error: require_once(): Failed opening required 'processor.php' (include_path='/srv/magento/app/code/local:/srv/magento/app/code/community:/srv/magento/app/code/core:/srv/magento/lib:.:/usr/local/lib/php') in /srv/magento/.modman/CodebaseExceptions/errors/report.php on line 27
```

**Comment by tmotyl** [comment]
that's right.

**Comment by kyrylo** [comment]
I just tried your patch and I don't think it fixes the issue.

**Comment by kyrylo** [comment]
I opened a new PR, that fixes the issue: https://github.com/airbrake/Airbrake-Magento/pull/7

**Pull request merged**
